version: "3.1"
services:
  hazelcast:
    image: hazelcast/hazelcast
    ports:
      - "5701:5701"
  management-center:
    image: hazelcast/management-center
    ports:
      - "8081:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
  user-management-db:
    container_name: user-management-database
    image: postgres:15-alpine
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./.data/db:/var/lib/postgresql/data
  user-management:
    depends_on:
      - user-management-db
      - hazelcast
    container_name: user-management-app
    image: user-management:1.0
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    environment:
      DATABASE_HOST: user-management-db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      APPLICATION_PORT: ${APPLICATION_PORT}
      HAZELCAST_CLUSTER_ADDRESS: hazelcast